### ISSUE TITLE
容器部署的时候 ip不固定导致每次都会新增节点

### ISSUE THREAD

**Issue by baqqioku** [imadcn/idworker#19]
1.容器环境下的问题
com.imadcn.framework.idworker.register.AbstractWorkerRegister#checkNodeInfo这个方法
![image](https://user-images.githubusercontent.com/5753857/221498163-3bb4cb08-df96-49b1-88fa-e86f7454a4a4.png)

比较ip的地方的地方

2. 生产进行kill pid 的时候，没有触发关闭的勾子，节点没有正常的删除
    com.imadcn.framework.idworker.generator.SnowflakeGenerator#close

**Comment by imadcn** [comment]
1、旧版本容器下请尝试不用磁盘外挂，另，1.6.0 移除了此判断

2、fixed in 1.6.0，如果还有问题，请反馈
