### ISSUE TITLE
注册成功后断线重连的bug

### ISSUE THREAD

**Issue by songg** [imadcn/idworker#4]
如果第一台机注册workId成功并初始化了snowflake后断线了, 然后另外一台机又注册上来抢占了这个workId那这个集群里面如果不重启第一台机不是有两个重复的workId了？这个会有重复Id的风险吗？

**Comment by imadcn** [comment]
server与zk的链接断开，server会挂起ID生成服务，不再产生新ID，等待重连；
重连成功以后会重新注册workerId（根据SessionId等判断是否是同一会话，是的话复用之前的workerId），因此同一台机器，同一时间只会拥有一个可用的workerId；
重连过程中如果产生了新的session，那么旧的workerId会被zk释放掉，供其他机器使用

**Comment by songg** [comment]
`	/**
	 * 初始化
	 */
	public void init() {
		long workerId = storage.register();
		if (workerId >= 0) {
			snowflake = Snowflake.create(workerId);
		} else {
			throw new RegException("failed to get worker id");
		}
	}

`

这段注册代码只会在启动的时候执行一次， 成功启动后如果再发生链接断开的情况，就算session都已经释放，这时snowflake 已经生成了。

而获取id的方法：
`	@Override
	public long nextId() {
		return snowflake.nextId();
	}`

这里似乎不能挂起ID生成服务，还是能继续生成ID吧。

**Comment by imadcn** [comment]
少年，似乎你的版本不对？看这个
[https://github.com/imadcn/idworker/blob/master/src/main/java/com/imadcn/framework/idworker/generator/SnowflakeGenerator.java](SnowflakeGenerator)

**Comment by songg** [comment]
看来我的版本太低了。我去更新一下。多谢。
