### ISSUE TITLE
生成的id前四位固定怎么修改

### ISSUE THREAD

**Issue by j2eegis** [imadcn/idworker#7]
**生成的id全是1988开头？**
198817147072282626
198866713354285056
198867018858999808

这是怎么回事？怎么显示成当前年份？或者开头数字随机

**Comment by imadcn** [comment]
详见[Snowflake](https://github.com/imadcn/idworker/blob/master/src/main/java/com/imadcn/framework/idworker/algorithm/Snowflake.java)算法注释
